import assert from 'node:assert/strict';
import fs from 'node:fs';
import {localParserAssets} from './local_parser_assets.mjs';
import {localPdfOptions} from '../src/platform/local-pdf-options.js';
import {readPresalesFile} from '../src/platform/nonstandard-file-reader.js';
const options=localPdfOptions('https://test.invalid/platform/index.html');
assert.equal(options.cMapUrl,'https://test.invalid/platform/vendor/pdfjs/cmaps/');
assert.equal(options.standardFontDataUrl,'https://test.invalid/platform/vendor/pdfjs/standard_fonts/');
assert.equal(options.wasmUrl,'https://test.invalid/platform/vendor/pdfjs/wasm/');
assert.equal(options.isEvalSupported,false);assert.equal(options.enableScripting,false);assert.equal(options.enableXfa,false);
const assets=localParserAssets(),manifest=JSON.parse(assets.get('vendor/parser-manifest.json'));
assert.equal(manifest.versions['pdfjs-dist'],'6.3.289');
assert.ok(assets.has('vendor/pdfjs/pdf.worker.mjs'));assert.ok(assets.has('vendor/mammoth/mammoth.browser.min.js'));
assert.ok(assets.has('vendor/xlsx/reader.min.js'));assert.ok(assets.has('vendor/xlsx/style-writer.min.js'));
assert.ok([...assets.keys()].some(p=>p.endsWith('.bcmap')));assert.ok([...assets.keys()].some(p=>p.endsWith('.wasm')));
assert.ok([...assets.keys()].every(p=>!p.endsWith('.map') && !/\.(pdf|xlsx|docx)$/.test(p)));
const html=fs.readFileSync('index.html','utf8');
assert.ok(!/https?:\/\/[^'"\s]*(?:cdnjs|cdn\.jsdelivr|unpkg)/.test(html));
assert.match(html,/XLSX\[key\] = XLSXReader\[key\]/);
assert.match(html,/localPdfDocumentOptions\(\)/);
const readerSource=fs.readFileSync('src/platform/nonstandard-file-reader.js','utf8');
assert.match(readerSource,/externalFileAccess:false/);assert.ok(!readerSource.includes('https://'));
const file={name:'test.pdf',size:8,arrayBuffer:async()=>new Uint8Array([37,80,68,70]).buffer};
let destroyed=false,cleanup=0,received;
const pdf={numPages:3,getPage:async i=>({getTextContent:async()=>({items:i===2?[]:[{str:`TEST page${i}`,hasEOL:true}]}),cleanup:()=>cleanup++})};
const task = document => ({promise:Promise.resolve(document),destroy:async()=>{destroyed=true;}});
const libs={document:{baseURI:'https://test.invalid/platform/'},pdfjsLib:{getDocument:v=>{received=v;return task(pdf);}}};
const parsed=await readPresalesFile(file,libs);
assert.deepEqual(parsed.segments.map(s=>s.page),[1,3]);assert.match(parsed.warnings[0],/第2页/);
assert.equal(received.isEvalSupported,false);assert.equal(received.enableScripting,false);assert.equal(destroyed,true);assert.equal(cleanup,3);
const loading={document:libs.document,localParserReady:{pdfjsLib:Promise.resolve().then(()=>{loading.pdfjsLib=libs.pdfjsLib;})}};
assert.equal((await readPresalesFile(file,loading)).type,'pdf','异步主库等待后读入');
await assert.rejects(()=>readPresalesFile(file,{localParserReady:{pdfjsLib:Promise.reject(new Error('test missing module'))}}),/本机解析组件加载失败/);
await assert.rejects(()=>readPresalesFile(file,{}),/本机解析组件未加载/);
await assert.rejects(()=>readPresalesFile({...file,name:'empty.pdf'},{...libs,pdfjsLib:{getDocument:()=>task({...pdf,numPages:1,getPage:async()=>({getTextContent:async()=>({items:[]}),cleanup(){}})})}}),/有效文字/);
await assert.rejects(()=>readPresalesFile(file,{...libs,pdfjsLib:{getDocument:()=>task({...pdf,numPages:151})}}),/150页/);
assert.equal(destroyed,true);
destroyed=false;
await assert.rejects(()=>readPresalesFile(file,{...libs,pdfjsLib:{getDocument:()=>({promise:Promise.reject(new Error('损坏PDF')),destroy:async()=>{destroyed=true;}})}}),/损坏PDF/);
assert.equal(destroyed,true,'失败的loadingTask也必须释放');
// No dependency on global browser DOM for basic workbook engine identity.
const workbook={SheetNames:['TEST'],Sheets:{TEST:{A1:{v:'额定电流：32A'}}}};
const modern={read:()=>workbook,utils:{decode_cell:()=>({r:0,c:0})}};
const workbookFile={...file,name:'test.xlsx',arrayBuffer:async()=>new Uint8Array([0x50,0x4b,3,4]).buffer};
assert.equal((await readPresalesFile(workbookFile,{XLSXReader:modern,XLSX:{read:()=>{throw new Error('旧读取器不得被调用');}}})).type,'xlsx');
await assert.rejects(()=>readPresalesFile(workbookFile,{localParserReady:{},XLSX:modern}),/本机解析组件未加载/,'CE缺失不能退回旧写出包读取');
await assert.rejects(()=>readPresalesFile({...file,name:'假.xlsx'},{XLSXReader:modern}),/不是有效的XLSX/,'不允许SheetJS将任意文本当作XLSX');
console.log(`本机解析依赖/许可清单、子路径参数、异步/失败保护与读取器身份测试通过（${assets.size}资源，合成软件验收）`);
