import assert from 'node:assert/strict';
import { PRODUCT_PROFILES, createPresalesPackage, addEquipment, updateEquipmentQuantity, addPresalesSource,
  replacePresalesSource, addRequirement, confirmPresalesRequirement, adoptPresalesScheme, confirmPresalesScheme,
  schemeReviewProblems, buildPresalesDeliverable, createPresalesSnapshot, restorePresalesSnapshot,
  verifyPresalesEvidence, adoptBuswayPresalesScheme, revisePresalesRequirement } from '../src/modules/nonstandard-presales.js';
import { createSmartBuswayDesign, calculateSmartBuswayDesign } from '../src/modules/engineering-calculators.js';
import { normalizeProject, SCHEMA_VERSION } from '../src/platform/project-schema.js';

// 合成软件测试，不是客户参数、真实型号或技术承诺。
assert.deepEqual(Object.keys(PRODUCT_PROFILES), ['cabinet', 'pdu', 'busway']);
assert.equal(Object.isFrozen(PRODUCT_PROFILES.pdu.fields.pduType.options), true);
assert.equal(PRODUCT_PROFILES.cabinet.fields.shortCircuitDurationS.unit, 's');
let pack = createPresalesPackage('合成软件用例');
assert.throws(() => addEquipment(pack, { category: 'ups', label: '错误品类' }, '测试'), /品类/);
assert.throws(() => addEquipment(pack, { category: 'cabinet', label: 'A', quantity: 0 }, '测试'), /数量/);
pack = addEquipment(pack, { category: 'cabinet', label: '柜A', quantity: 2 }, '合成设备');
const a = pack.equipment[0].id;
pack = addEquipment(pack, { category: 'cabinet', label: '柜B' }, '合成设备');
const b = pack.equipment[1].id;
assert.equal(pack.equipment[1].quantity, null);
const raw = '柜A额定电流630A；柜B额定电流250A；柜A澄清电流800A；柜尺寸按图；供货边界含柜体。';
pack = addPresalesSource(pack, { type: 'pdf', name: 'C:/私有目录/合成.pdf', text: raw, segments: [{ start: 0, end: raw.length, page: 12 }] }, '合成文本');
const sourceId = pack.sources[0].id;
assert.equal(pack.sources[0].name, '合成.pdf');
assert.throws(() => addPresalesSource(pack, { type: 'xlsx', name: '表', text: raw, segments: [{ start: 0, end: raw.length }] }, '测试'), /表名/);
function evidence(quote) { const start = raw.indexOf(quote); return { sourceId, quote, start, end: start + quote.length }; }
const requirement = (equipmentId, value, quote) => ({ equipmentId, field: 'ratedCurrentA', forbiddenDeviation: false, candidates: [{ value, evidence: evidence(quote) }] });
pack = addRequirement(pack, requirement(a, 630, '柜A额定电流630A'), '合成提取');
const ra = pack.requirements[0].id;
pack = addRequirement(pack, requirement(b, 250, '柜B额定电流250A'), '合成提取');
assert.equal(pack.requirements.every(r => r.reviewStatus === 'pending'), true, '不同设备不会冲突');
assert.throws(() => addRequirement(pack, requirement(a, 6300, '柜A额定电流630A'), '伪证据'), /证据/);
assert.equal(verifyPresalesEvidence(pack, { ...evidence('柜A额定电流630A'), end: 10000 }, 630), false);
pack = addRequirement(pack, requirement(a, 800, '柜A澄清电流800A'), '合成追加');
assert.equal(pack.requirements.length, 2, '同设备标量字段只保留一个要求池');
assert.equal(pack.requirements[0].reviewStatus, 'conflict');
assert.equal(pack.requirements[0].candidates.length, 2);
assert.throws(() => confirmPresalesRequirement(pack, ra, { value: 800, response: 'met' }, ''), /原因/);
pack = confirmPresalesRequirement(pack, ra, { value: 800, response: 'met', forbiddenDeviation: true }, '合成澄清以800为准');
assert.deepEqual(pack.revisions.at(-1).detail.from.confirmedValue, null);
assert.equal(pack.revisions.at(-1).detail.to.confirmedValue, 800);
assert.throws(() => confirmPresalesRequirement(pack, ra, { value: 800, response: 'deviation' }, '测试'), /禁止偏离/);
assert.throws(() => confirmPresalesRequirement(pack, ra, { value: null, response: 'met' }, '测试'), /未知/);
pack = addRequirement(pack, { equipmentId: b, field: 'widthMm', candidates: [{ value: '按图', evidence: evidence('柜尺寸按图') }] }, '合成按图');
assert.equal(pack.requirements.at(-1).reviewStatus, 'unknown');
assert.equal(pack.requirements.at(-1).candidates[0].value, null);

const component = { name: '合成开关', specification: '软件测试规格', quantity: 3, unit: '个', model: 'SYNTHETIC-TEST', modelStatus: 'verified', reference: '合成测试依据（非真实厂家资料）', requirementIds: [ra] };
const scheme = { equipmentId: a, name: '柜A合成方案', config: { ratedCurrentA: 800, supplyBoundary: '含柜体', spareCount: 0 }, components: [component], requirementIds: [ra] };
assert.throws(() => adoptPresalesScheme(pack, { ...scheme, config: { unsupported: 1 } }, '测试'), /字段/);
assert.throws(() => adoptPresalesScheme(pack, { ...scheme, config: { ratedCurrentA: false } }, '测试'), /数值/);
assert.throws(() => adoptPresalesScheme(pack, { ...scheme, requirementIds: [pack.requirements[1].id] }, '测试'), /跨设备/);
assert.throws(() => adoptPresalesScheme(pack, { ...scheme, components: [{ ...component, model: '', reference: '' }] }, '测试'), /核对/);
pack = adoptPresalesScheme(pack, scheme, '合成采用');
const sid = pack.schemes[0].id;
assert.deepEqual(schemeReviewProblems(pack, sid), []);
assert.equal(buildPresalesDeliverable(pack, sid).status, 'discussion-draft');
pack = confirmPresalesScheme(pack, sid, '合成售前复核');
let output = buildPresalesDeliverable(pack, sid);
assert.equal(output.status, 'reviewed-presales');
assert.equal(output.bom[0].totalQuantity, 6);
assert.equal(output.bom[0].equipmentId, a);
assert.equal(output.bom[0].packageRevision, output.packageRevision);
assert.equal(output.config.ratedCurrentA, pack.schemes[0].config.ratedCurrentA);
assert.match(output.boundary, /非生产图纸/);
const snapshot = createPresalesSnapshot(pack), baseline = JSON.stringify(snapshot);
output.config.ratedCurrentA = 1;
assert.equal(pack.schemes[0].config.ratedCurrentA, 800, '导出不回写');
pack = updateEquipmentQuantity(pack, a, 4, '合成数量修订');
assert.equal(pack.schemes[0].reviewStatus, 'pending');
assert.equal(buildPresalesDeliverable(pack, sid).bom[0].totalQuantity, 12);
assert.equal(JSON.stringify(snapshot), baseline, '修订不改变旧快照');
const restored = restorePresalesSnapshot(JSON.parse(baseline));
assert.equal(restored.equipment[0].quantity, 2);
assert.equal(restored.schemes[0].reviewStatus, 'pending');
assert.equal(restored.requirements[0].reviewStatus, 'pending', '恢复不自动放行');
const cleared = revisePresalesRequirement(pack, ra, null, '合成撤销要求');
assert.equal(cleared.requirements[0].confirmedValue, null);
assert.equal(cleared.requirements[0].reviewStatus, 'unknown');
assert.equal(cleared.schemes[0].reviewStatus, 'pending');
assert.equal(cleared.revisions.at(-1).detail.from.confirmedValue, 800);
assert.equal(cleared.revisions.at(-1).detail.to.confirmedValue, null);
assert.equal(pack.requirements[0].confirmedValue, 800, '修订不回写');
assert.throws(() => restorePresalesSnapshot({ ...snapshot, contractVersion: 2 }), /版本/);
const corrupt = JSON.parse(baseline); corrupt.package.requirements[0].candidates[0].evidence.quote = '伪造';
assert.throws(() => restorePresalesSnapshot(corrupt), /证据/);
const duplicate = JSON.parse(baseline);
duplicate.package.requirements.push({ ...duplicate.package.requirements[0], id: 'DUPLICATE-TEST' });
assert.throws(() => restorePresalesSnapshot(duplicate), /重复/);
const configCorrupt = JSON.parse(baseline); configCorrupt.package.schemes[0].config.ratedCurrentA = [800];
assert.throws(() => restorePresalesSnapshot(configCorrupt), /数值/);
const unassigned = addRequirement(pack, { equipmentId: null, field: 'clause', candidates: [{ value: '含柜体', evidence: evidence('供货边界含柜体') }] }, '合成未分配条款');
assert.ok(schemeReviewProblems(unassigned, sid).some(p => p.includes('未分配')));
pack = adoptPresalesScheme(pack, { ...scheme, id: sid, config: { ratedCurrentA: 630, supplyBoundary: '含柜体' } }, '合成不一致');
assert.ok(schemeReviewProblems(pack, sid).some(p => p.includes('不一致')));
const replacement = raw.replace('630A', '6300A');
pack = replacePresalesSource(pack, sourceId, { type: 'pdf', name: '合成.pdf', text: replacement, segments: [{ start: 0, end: replacement.length, page: 13 }] }, '合成重传');
assert.equal(pack.requirements[0].reviewStatus, 'stale');
assert.throws(() => confirmPresalesRequirement(pack, ra, { value: 800, response: 'met' }, '测试'), /重新提取/);

let pdu = addEquipment(createPresalesPackage(), { category: 'pdu', label: '测试PDU' }, '测试');
pdu = adoptPresalesScheme(pdu, { equipmentId: pdu.equipment[0].id, name: '未知PDU讨论稿', config: {}, components: [{ name: '功能项', specification: '待选型', quantity: null, unit: '个' }] }, '测试');
const pduOutput = buildPresalesDeliverable(pdu, pdu.schemes[0].id);
assert.equal(pduOutput.bom[0].totalQuantity, null);
assert.equal(pduOutput.bom[0].code, '');
assert.equal(pduOutput.bom[0].modelStatus, 'pending');
assert.ok(pduOutput.clarifications.some(p => p.includes('PDU类型')));
assert.throws(() => confirmPresalesScheme(pdu, pdu.schemes[0].id, '测试'), /待确认/);

let busway = addEquipment(createPresalesPackage(), { category: 'busway', label: '合成母线', quantity: 1 }, '合成设备');
const bid = busway.equipment[0].id;
const design = createSmartBuswayDesign({ row1: { cabinets600: 2 }, row2: {}, defaultPowerKw: 5, topology: 'single' });
const designBaseline = JSON.stringify(design);
const expected = calculateSmartBuswayDesign(structuredClone(design));
busway = adoptBuswayPresalesScheme(busway, bid, { ...design, result: { bom: [{ code: 'FAKE' }] } }, '复用采用配置');
const bridge = buildPresalesDeliverable(busway, busway.schemes[0].id);
assert.deepEqual(bridge.bom.map(row => [row.code, row.perEquipmentQuantity]), expected.bom.map(row => [row.code || '', row.quantity]));
assert.equal(bridge.bom.every(row => row.modelStatus === 'pending'), true, '旧目录ok不自动变厂家verified');
assert.equal(JSON.stringify(design), designBaseline, '桥接不改旧输入');
assert.throws(() => adoptBuswayPresalesScheme(busway, bid, {}, '测试'), /布局/);
const excessive = createSmartBuswayDesign({ row1: { cabinets600: 100 }, row2: {}, defaultPowerKw: 50, topology: 'single' });
assert.throws(() => adoptBuswayPresalesScheme(busway, bid, excessive, '测试'), /阻断/);
const underRated = createSmartBuswayDesign({ row1: { cabinets600: 15 }, row2: {}, defaultPowerKw: 10, topology: 'single',
  runSelections: { '0-A': { mode: 'manual', buswayRatedCurrentA: 160, terminalLinked: true } } });
// 键由旧工具自身约定；显式覆盖实际运行键以验证采用不足额定值。
const underResult = calculateSmartBuswayDesign(underRated);
for (const key of Object.keys(underResult.design.runSelections)) underResult.design.runSelections[key] = { mode: 'manual', buswayRatedCurrentA: 160, terminalLinked: true };
assert.throws(() => adoptBuswayPresalesScheme(busway, bid, underResult.design, '测试'), /阻断/);
const legacy = normalizeProject({ schemaVersion: 2, name: '旧工具数据', ups: { custom: 123 }, busbars: { smartBuswayDesign: design } });
assert.equal(SCHEMA_VERSION, 2); assert.equal(legacy.ups.custom, 123); assert.equal(legacy.busbars.smartBuswayDesign, design);
console.log('非标售前契约与共用纯逻辑回归通过（合成用例；非业务验收）');
