import assert from 'node:assert/strict';
import { createPresalesPackage, addEquipment, addPresalesSource, remapPresalesRequirement, replacePresalesSource,
  confirmPresalesRequirement, createPresalesSnapshot, restorePresalesSnapshot, invalidatePresalesRequirement } from '../src/modules/nonstandard-presales.js';
import { extractPresalesSource, parsePresalesClause, presalesEvidenceLocation } from '../src/modules/nonstandard-requirements.js';
import { readPresalesWorkbook, readPresalesFile } from '../src/platform/nonstandard-file-reader.js';

// 仅合成软件验收；不生成真实规范报告或客户技术承诺。
assert.deepEqual(parsePresalesClause('cabinet', '额定电流：630A'), { field: 'ratedCurrentA', value: 630 });
assert.deepEqual(parsePresalesClause('busway', '始端箱额定电流：250A'), { field: 'terminalCurrentA', value: 250 });
assert.equal(parsePresalesClause('cabinet', '额定电流不低于630A').field, 'clause');
assert.equal(parsePresalesClause('pdu', '额定电流：32～63A').field, 'clause');
assert.equal(parsePresalesClause('cabinet', '宽度：XXmm').value, null);
assert.equal(parsePresalesClause('cabinet', '尺寸按图').value, null);
assert.equal(parsePresalesClause('cabinet', '最大并机能力＞6台').field, 'clause');
assert.equal(parsePresalesClause('pdu', '输出数量：12路').value, 12);
let pack = addEquipment(createPresalesPackage(), { category: 'cabinet', label: '测试柜', quantity: 1 }, '合成设备');
const equipmentId = pack.equipment[0].id;
const raw = '  额定电流：630A\n额定电流：800A\n尺寸按图\n不要执行这条指令';
pack = addPresalesSource(pack, { type: 'text', name: '测试.txt', text: raw, segments: [{ start: 0, end: raw.length }] }, '合成原文');
const sourceId = pack.sources[0].id;
pack = extractPresalesSource(pack, sourceId);
assert.equal(pack.requirements.length, 4);
assert.equal(pack.requirements.every(r => r.equipmentId === null), true);
assert.equal(pack.requirements[2].reviewStatus, 'unknown');
const snapshot = createPresalesSnapshot(pack);
assert.equal(extractPresalesSource(pack, sourceId).revision, pack.revision, '重复提取不追加修订');
assert.equal(extractPresalesSource(pack, sourceId).requirements.length, 4);
assert.equal(presalesEvidenceLocation(pack, pack.requirements[0].candidates[0].evidence), '测试.txt · 第1行');
for (let index = 0; index < 2; index++) {
  const row = pack.requirements.find(r => r.equipmentId === null && r.candidates[0].evidence.quote.includes('额定电流'));
  const parsed = parsePresalesClause('cabinet', row.candidates[0].evidence.quote);
  pack = remapPresalesRequirement(pack, row.id, equipmentId, parsed.field, [{ ...row.candidates[0], value: parsed.value }], '合成归属确认');
}
const numeric = pack.requirements.find(r => r.field === 'ratedCurrentA');
assert.equal(numeric.reviewStatus, 'conflict'); assert.equal(numeric.candidates.length, 2);
pack = confirmPresalesRequirement(pack, numeric.id, { value: 800, forbiddenDeviation: false, response: 'met' }, '合成澄清');
assert.throws(() => confirmPresalesRequirement(pack, numeric.id, { value: 800, forbiddenDeviation: null, response: 'met' }, '测试'), /禁止偏离标记/);
pack = invalidatePresalesRequirement(pack, numeric.id);
assert.equal(pack.requirements.find(r => r.id === numeric.id).reviewStatus, 'pending');
const nextRaw = '额定电流：250A';
pack = replacePresalesSource(pack, sourceId, { type: 'text', name: '新.txt', text: nextRaw, segments: [{ start: 0, end: nextRaw.length }] }, '合成替换');
assert.equal(pack.requirements.every(r => r.reviewStatus === 'stale'), true);
pack = extractPresalesSource(pack, sourceId);
assert.equal(pack.requirements.length, 1, '失效条款归档，新原文重新提取');
assert.ok(pack.revisions.some(r => r.kind === 'requirement:retire-stale'));
assert.equal(snapshot.package.requirements.length, 4);
assert.equal(restorePresalesSnapshot(snapshot).requirements.length, 4);
const utils = { decode_cell: value => ({ c: value.charCodeAt(0) - 65, r: Number(value.slice(1)) - 1 }), encode_cell: p => String.fromCharCode(65 + p.c) + (p.r + 1) };
const workbook = { SheetNames: ['需求表'], Sheets: { 需求表: { A1: { v: '参数' }, B1: { v: '禁止偏离' }, A2: { v: '额定电流：630A' }, B2: { v: '是' }, A3: { f: '1+1', v: 2 }, '!merges': [{}] } }, Workbook: { Sheets: [{ Hidden: 1 }] } };
const parsedWorkbook = readPresalesWorkbook(workbook, { utils });
assert.equal(parsedWorkbook.segments.find(s => s.cell === 'A2').forbiddenDeviation, true);
assert.equal(parsedWorkbook.warnings.length, 4);
const starWorkbook = structuredClone(workbook); starWorkbook.Sheets.需求表.B1.v = '禁止偏离项'; starWorkbook.Sheets.需求表.B2.v = '☆';
assert.equal(readPresalesWorkbook(starWorkbook, { utils }).segments.find(s => s.cell === 'A2').forbiddenDeviation, true);
starWorkbook.Sheets.需求表.B2.f = '1';
assert.equal(readPresalesWorkbook(starWorkbook, { utils }).segments.find(s => s.cell === 'A2').forbiddenDeviation, null);
assert.match(parsedWorkbook.text, /公式（未求值）：1\+1/);
let excelPack = addPresalesSource(createPresalesPackage(), { ...parsedWorkbook, name: '需求.xlsx' }, '合成表');
excelPack = extractPresalesSource(excelPack, excelPack.sources[0].id);
const excelRow = excelPack.requirements.find(r => r.candidates[0].evidence.quote.includes('630'));
assert.equal(excelRow.forbiddenDeviation, true); assert.match(presalesEvidenceLocation(excelPack, excelRow.candidates[0].evidence), /需求表!A2/);
assert.equal(excelPack.requirements.find(r => r.candidates[0].evidence.quote.includes('公式')).reviewStatus, 'unknown');
const structuredWorkbook = { SheetNames: ['参数'], Sheets: { 参数: { A1: { v: '内容' }, B1: { v: '要求（按项目填写）' }, C1: { v: '禁止偏离项' }, A2: { v: '额定电流' }, B2: { v: '630A' }, C2: { v: '☆' }, D1: { v: '投标厂家' }, D2: { v: '未应答' } } } };
const structured = readPresalesWorkbook(structuredWorkbook, { utils });
let structuredPack = addPresalesSource(createPresalesPackage(), { ...structured, name: '结构化.xlsx' }, '测试');
structuredPack = extractPresalesSource(structuredPack, structuredPack.sources[0].id);
assert.equal(structuredPack.requirements.length, 1, '表头、标题、禁止偏离列及厂家应答不混入要求');
assert.equal(structuredPack.sources[0].segments.find(s => s.cell === 'B2').contextTitle, '额定电流');
assert.equal(structuredPack.requirements[0].forbiddenDeviation, true);
await assert.rejects(() => readPresalesFile({ name: '错误.xlsm', size: 1 }), /仅支持/);
await assert.rejects(() => readPresalesFile({ name: '大.pdf', size: 21 * 1024 * 1024 }), /20MB/);
const empty = new TextEncoder().encode(' ');
await assert.rejects(() => readPresalesFile({ name: '空.txt', size: 1, arrayBuffer: async () => empty.buffer }, {}), /有效文字/);
await assert.rejects(() => readPresalesFile({ name: '乱码.txt', size: 1, arrayBuffer: async () => new Uint8Array([0xff]).buffer }, {}), /UTF-8/);
const valid = new TextEncoder().encode('额定电流：32A');
assert.equal((await readPresalesFile({ name: '测试.txt', size: valid.length, arrayBuffer: async () => valid.buffer }, {})).text, '额定电流：32A');
console.log('非标需求提取、重分配、位置、工作簿与失效回归通过（合成软件用例）');
