import assert from 'node:assert/strict';
import { createPresalesPackage,addEquipment,addPresalesSource,addRequirement,adoptPresalesScheme,
  createPresalesSnapshot,restorePresalesSnapshot,buildPresalesDeliverable,confirmPresalesScheme,
  replacePresalesSource,confirmPresalesRequirement } from '../src/modules/nonstandard-presales.js';
import { parsePduSpecClause } from '../src/modules/pdu-rules.js';
import { createPduProposal } from '../src/modules/pdu-assistant.js';
import { buildPresalesOutput,presalesReportHtml } from '../src/modules/nonstandard-deliverable.js';

// 明确合成软件用例；不是客户已确认方案。
const spec = '采用输入AC230V 32A,输出12位国标三孔10A插座+2位国标三孔16A插座，具体规格后续设计联络最终确定。';
const facts = parsePduSpecClause(spec);
assert.deepEqual(facts.config,{voltageV:230,ratedCurrentA:32,outputCount:14});
assert.deepEqual(facts.outputs.map(r=>r.quantity),[12,2]); assert.equal(facts.tentative,true);
assert.equal(parsePduSpecClause('输入AC230V 32A～63A').config.ratedCurrentA,undefined);
assert.equal(parsePduSpecClause('输入AC230V 32A/63A').config.ratedCurrentA,undefined);
assert.equal(parsePduSpecClause('输入AC230V 32A以上').config.ratedCurrentA,undefined);
assert.equal(parsePduSpecClause('至少输入AC230V 32A').config.ratedCurrentA,undefined);
assert.equal(parsePduSpecClause('输入电压不低于230V、电流32A').config.voltageV,undefined);
for (const quote of ['输出12位国标10A插座+XX位国标16A插座','输出至少12位国标10A插座','输出12位国标10A插座或8位国标16A插座','输出12位国标10A插座+备用2位']) {
  assert.equal(parsePduSpecClause(quote).outputs.length,0,quote);
  assert.equal(parsePduSpecClause(quote).config.outputCount,undefined);
}
assert.throws(()=>parsePduSpecClause('输出9007199254740992位国标10A插座'),/安全整数/);
assert.throws(()=>parsePduSpecClause('输出0位国标10A插座'),/安全整数/);
let pack = addEquipment(createPresalesPackage('合成PDU助手'),{category:'pdu',label:'TEST-A',quantity:3},'合成区域登记');
pack = addEquipment(pack,{category:'pdu',label:'TEST-B',quantity:2},'合成区域登记');
const eid = pack.equipment[0].id;
const add = (p,quote,field='clause',value=quote,equipmentId=eid) => {
  const next = addPresalesSource(p,{type:'text',name:'合成要求.txt',text:quote,segments:[{start:0,end:quote.length}]},'合成来源');
  return addRequirement(next,{equipmentId,field,candidates:[{value,evidence:{sourceId:next.sources.at(-1).id,start:0,end:quote.length,quote}}]},'合成要求');
};
pack = add(pack,spec);
pack = add(pack,'每个机柜标配2条PDU，为设备A/B路供电使用。');
pack = add(pack,'机柜级PDU需能提供插座级监控信息，并能对插座实现远程上下电控制。');
pack = add(pack,'配热插拔液晶电表，具备本地计量检测功能。');
pack = add(pack,'PDU须与上端母线插接箱同品牌产品。');
const ids = pack.requirements.map(r=>r.id);
const options = {requirementIds:ids,config:{pduType:'rack'}};
const before = JSON.stringify(pack),proposal=createPduProposal(pack,eid,options);
assert.equal(JSON.stringify(pack),before,'纯生成不突变');
assert.equal(proposal.config.outputCount,14); assert.equal(proposal.config.phase,undefined);
assert.equal(proposal.config.inputCount,undefined); assert.equal(proposal.config.branchCount,undefined);
assert.equal(proposal.components.find(c=>c.role==='input').quantity,null,'不默认输入接口1');
assert.deepEqual(proposal.components.filter(c=>c.role==='output').map(c=>c.quantity),[12,2]);
assert.ok(proposal.components.filter(c=>c.role==='output').every(c=>c.risk.includes('待确认')));
assert.ok(proposal.components.every(c=>!c.model && !c.code && !c.brand && c.modelStatus==='pending'));
assert.ok(proposal.components.filter(c=>c.role==='accessory').every(c=>c.quantity===null));
assert.ok(proposal.config.brandRequirement.includes('同品牌'));
assert.equal(pack.equipment[0].quantity,3,'不再乘每柜数量');
assert.throws(()=>createPduProposal(pack,eid,{...options,config:{}}),/机架PDU/);
assert.throws(()=>createPduProposal(pack,eid,{...options,config:{pduType:'cabinet'}}),/机架PDU/);
assert.throws(()=>createPduProposal(pack,pack.equipment[1].id,options),/跨设备/);
assert.throws(()=>createPduProposal(pack,eid,{...options,requirementIds:[]}),/明确选择/);
assert.throws(()=>createPduProposal(pack,eid,{...options,config:{pduType:'rack',ratedCurrentA:63}}),/不一致/);
const bad=structuredClone(pack); bad.requirements[0].candidates[0].evidence.quote='伪造';
assert.throws(()=>createPduProposal(bad,eid,options),/证据不匹配/);
const stale=replacePresalesSource(pack,pack.sources[0].id,{type:'text',name:'替换.txt',text:'新要求',segments:[{start:0,end:3}]},'合成替换');
assert.throws(()=>createPduProposal(stale,eid,options),/失效/);
let conflict=add(pack,'输入AC240V 32A，输出12位国标三孔10A插座+2位国标三孔16A插座');
assert.throws(()=>createPduProposal(conflict,eid,{...options,requirementIds:conflict.requirements.map(r=>r.id)}),/不同原文候选/);
conflict=add(pack,'输出7位国标三孔10A插座+7位国标三孔16A插座');
assert.throws(()=>createPduProposal(conflict,eid,{...options,requirementIds:conflict.requirements.map(r=>r.id)}),/不同插座组合/);
let partial=add(pack,'输出XX位国标10A插座');
const unresolved=createPduProposal(partial,eid,{...options,requirementIds:partial.requirements.map(r=>r.id)});
assert.equal(unresolved.config.outputCount,undefined); assert.ok(unresolved.components.some(c=>c.role==='output' && c.quantity===null));
let inputRange=add(pack,'输入AC230V 32A/63A');
const uncertain=createPduProposal(inputRange,eid,{...options,requirementIds:inputRange.requirements.map(r=>r.id)});
assert.equal(uncertain.config.ratedCurrentA,undefined);assert.equal(uncertain.config.voltageV,undefined);
let duplicate=add(pack,spec);
assert.deepEqual(createPduProposal(duplicate,eid,{...options,requirementIds:duplicate.requirements.map(r=>r.id)}).components.filter(c=>c.role==='output').map(c=>c.quantity),[12,2]);
let scalar=add(pack,'额定电流：63A','ratedCurrentA',63);
scalar=confirmPresalesRequirement(scalar,scalar.requirements.at(-1).id,{value:63,forbiddenDeviation:false,response:'met'},'合成确认');
assert.throws(()=>createPduProposal(scalar,eid,options),/已确认要求不一致/);
let saved=adoptPresalesScheme(pack,proposal,'合成采用候选');
const sid=saved.schemes.at(-1).id;
const out=buildPresalesDeliverable(saved,sid);
assert.equal(out.status,'discussion-draft');
assert.deepEqual(out.bom.filter(c=>c.role==='output').map(c=>c.totalQuantity),[36,6]);
assert.ok(out.description.some(p=>p.includes('插座14位')));
assert.throws(()=>confirmPresalesScheme(saved,sid,'合成尝试'),/待复核|待确认|型号待核对/);
const snapshot=createPresalesSnapshot(saved);
assert.equal(restorePresalesSnapshot(snapshot).schemes[0].reviewStatus,'pending');
const tampered=structuredClone(snapshot); tampered.package.schemes[0].assistant.sourceRevision=99999;
assert.throws(()=>restorePresalesSnapshot(tampered),/元数据非法/);
const other=structuredClone(snapshot); other.package.schemes[0].assistant.sourceRequirementIds=['不存在'];
assert.throws(()=>restorePresalesSnapshot(other),/不存在|跨设备/);
const revised={...saved.schemes[0],config:{...saved.schemes[0].config,outputCount:15},components:structuredClone(saved.schemes[0].components)};
revised.components.find(c=>c.role==='output').quantity=13;
saved=adoptPresalesScheme(saved,revised,'合成调整插座');
const data=buildPresalesOutput(saved,sid);
assert.ok(data.output.description.some(p=>p.includes('插座15位')));
assert.equal(data.output.bom.find(c=>c.role==='output').totalQuantity,39);
assert.ok(presalesReportHtml(data).includes('插座15位'));
assert.ok(data.tables.header.some(r=>r[1]==='PDU原文条款候选（未自动确认采用）'));
console.log('PDU有限语法、候选证据、设备隔离、未知/限定、数量、同源说明和兼容回归通过（合成软件验收）');
